# define pipeline number (https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=azure-devops&tabs=yaml#build-number-format)
name: 1.0$(Rev:.r)

# define resources (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#repository-resource)
resources:
  repositories:
    - repository: templates
      type: github
      name: kbrashears5/yaml
      endpoint: kbrashears5

# define build triggers (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#trigger)
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/*

# build projects and create nuget package
stages:
- template: templates/build-dotnet-core.yml@templates
  parameters:
    pack: true
      projects: '**/*.csproj'
      buildArguments: '-p:Configuration=Release'
      test: true
      testProjects: '**/*Tests.csproj'
      folder: ''
      pack: false
      filesToPack: '**/*.*proj'
      packageFolder: '$(Build.ArtifactStagingDirectory)'
      nuGetCredentials: 'NuGet'