# must go in the .github folder

# https://docs.github.com/en/github/administering-a-repository/about-github-dependabot
version: 2
updates:
  # package.json in root directory
  # https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem
  - package-ecosystem: "npm"
    # https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#directory
    directory: "/"
    # daily at 5am UTC
    # https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#scheduleinterval
    schedule:
      interval: "daily"
    # always get latest version
    # https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#versioning-strategy
    versioning-strategy: increase
    # set reviewers
    # https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#reviewers
    reviewers:
      - "kbrashears5"