# must go in the .github folder

# https://docs.github.com/en/github/administering-a-repository/about-github-dependabot
version: 2
updates:
  # package.json in root directory
  - package-ecosystem: "npm"
    directory: "/"
    # daily at 5am UTC
    schedule:
      interval: "daily"